"""
Django settings for photoproject project.

Generated by 'django-admin startproject' using Django 3.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os
from . import django_pass
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@(4ywdq3e(0tyzegpjdh=030j7ci-jjq2n3*jyq*p1hr!l2-c+'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'photoproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'photoproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'kpi',
        'USER': 'root',
        'PASSWORD': django_pass.mysqlpass,
        'HOST': '172.18.99.183',
        'PORT': '33006',
        'OPTIONS': {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGES = [
    ('zh-Hans', _('Chinese')),
]

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'     # 引用名，html页面使用
# STATIC_ROOT = "C:\\Users\\1214\\Desktop\\图片共享\\photoProject\\photoproject\\static"      # debug改为False需要设置，可以访问
STATIC_ROOT = os.path.join(BASE_DIR,'static')  # debug改为False需要设置，可以访问
MEDIA_URL="/images/"
MEDIA_ROOT="/mnt/images"
MEDIAHB_URL="/imageshaibao/"
MEDIAHB_ROOT="/mnt/imageshaibao"
MEDIAMJX_URL="/imagesmaijiaxiu/"
MEDIAMJX_ROOT="/mnt/imagesmaijiaxiu"
MEDIAPPDRT_URL="/imagespinpaidarentu/"
MEDIAPPDRT_ROOT="/mnt/imagespinpaidarentu"
MEDIAZHUTU_URL="/imageszhutu/"
MEDIAZHUTU_ROOT="/mnt/imageszhutu"
MEDIAOTHER_ROOT="/mnt/imagesother"
MEDIAOTHER_URL="/imagesother/"
MEDIASHITI_ROOT="/mnt/imagesshiti"
MEDIASHITI_URL="/imagesshiti/"
# MEDIA_ROOT="\\\\172.18.99.210"   # 不可以访问
# STATICFILES_DIRS = [
#     'R:\\',  #实际名，实际系统路径的根目录文件名
# ]

# MEDIA_ROOT=os.path.join(BASE_DIR,'media/').replace('\\','/') 
# MEDIA_ROOT="\\172.18.99.210"  
# MEDIA_URL="/data210/"
